export type Tool = {
  slug: string;
  name: string;
  description: string;
  category?: string;
  affiliateLink?: string;
};

export const tools: Tool[] = [
  { slug: 'word-counter', name: 'Word Counter', description: 'Count words and analyze text statistics.' },
  { slug: 'character-counter', name: 'Character Counter', description: 'Count characters, spaces, and paragraphs in real-time.' },
  { slug: 'ai-detector', name: 'AI Detector', description: 'Check if text was generated by AI.', affiliateLink: 'https://viralcanvas.ai/?ref=kyle' },
  { slug: 'grammar-checker', name: 'Grammar Checker', description: 'Find and fix grammar and spelling errors.' },
  { slug: 'case-converter', name: 'Case Converter', description: 'Convert text between different cases.' },
  { slug: 'invoice-generator', name: 'Invoice Generator', description: 'Create professional invoices easily.' },
  { slug: 'reading-time', name: 'Reading Time', description: 'Estimate how long it takes to read a text.' },
  { slug: 'roi-calculator', name: 'ROI Calculator', description: 'Calculate return on investment for marketing.' },
  { slug: 'salary-hourly-converter', name: 'Salary Hourly Converter', description: 'Convert annual salary to hourly wage.' },
  { slug: 'lorem-ipsum-generator', name: 'Lorem Ipsum Generator', description: 'Generate placeholder text for designs.' },
  { slug: 'password-generator', name: 'Password Generator', description: 'Create secure, random passwords.' },
  { slug: 'hashtag-generator', name: 'Hashtag Generator', description: 'Generate relevant hashtags for social media.' },
  { slug: 'resume-scorer', name: 'Resume Scorer', description: 'Analyze and score your resume.' },
  { slug: 'headline-analyzer', name: 'Headline Analyzer', description: 'Optimize your headlines for engagement.' },
  { slug: 'markdown-to-html', name: 'Markdown to HTML', description: 'Convert markdown text to HTML code.' },
  { slug: 'loan-calculator', name: 'Loan Calculator', description: 'Calculate monthly payments and total interest for any loan.' },
  { slug: 'qr-code-generator', name: 'QR Code Generator', description: 'Generate free QR codes for URLs, text, and more.' },
  { slug: 'keyword-density-checker', name: 'Keyword Density Checker', description: 'Analyze keyword frequency and density in your content.', affiliateLink: 'https://seranking.com/?ga=5009081&source=link' },
  { slug: 'break-even-calculator', name: 'Break-Even Calculator', description: 'Calculate the break-even point for your business or product.' },
  { slug: 'meta-tag-previewer', name: 'Meta Tag Previewer', description: 'Preview how your page title and meta description appear in Google search results.', affiliateLink: 'https://seranking.com/?ga=5009081&source=link' },
  { slug: 'email-subject-tester', name: 'Email Subject Tester', description: 'Score your email subject line for open rate potential.' },
];
