export type Tool = {
  slug: string;
  name: string;
  description: string;
  category?: string;
  affiliateLink?: string;
};

export const tools: Tool[] = [
  { slug: 'word-counter', name: 'Word Counter', description: 'Free online word counter tool to accurately track word count, character count, and text statistics for SEO and writing.' },
  { slug: 'character-counter', name: 'Character Counter', description: 'Real-time character counter tool that tracks characters with and without spaces, ideal for social media and meta tags.' },
  { slug: 'ai-detector', name: 'AI Detector', description: 'Advanced AI content detector to check if your text was generated by ChatGPT, Claude, or other AI writing tools.', affiliateLink: 'https://viralcanvas.ai/?ref=kyle' },
  { slug: 'grammar-checker', name: 'Grammar Checker', description: 'Free online grammar checker to find and fix spelling errors, punctuation mistakes, and improve your writing style.' },
  { slug: 'case-converter', name: 'Case Converter', description: 'Easily convert text between UPPERCASE, lowercase, Title Case, and sentence case with our free online converter.' },
  { slug: 'invoice-generator', name: 'Invoice Generator', description: 'Create professional PDF invoices for your business or freelance projects instantly with our free generator.' },
  { slug: 'reading-time', name: 'Reading Time', description: 'Calculate the estimated reading time for your articles and blog posts to improve user engagement.' },
  { slug: 'roi-calculator', name: 'ROI Calculator', description: 'Professional ROI calculator to measure the return on investment for your marketing campaigns and business projects.' },
  { slug: 'salary-hourly-converter', name: 'Salary Hourly Converter', description: 'Convert your annual salary to an hourly wage or vice versa to better understand your earnings and budget.' },
  { slug: 'lorem-ipsum-generator', name: 'Lorem Ipsum Generator', description: 'Generate custom Lorem Ipsum placeholder text for your web design and layout projects in various lengths.' },
  { slug: 'password-generator', name: 'Password Generator', description: 'Secure password generator to create strong, random passwords that protect your online accounts from hackers.' },
  { slug: 'hashtag-generator', name: 'Hashtag Generator', description: 'Find the best trending hashtags for your social media posts on Instagram, TikTok, and Twitter to increase reach.' },
  { slug: 'resume-scorer', name: 'Resume Scorer', description: 'Get an instant SEO score for your resume and tips on how to optimize it for Applicant Tracking Systems (ATS).' },
  { slug: 'headline-analyzer', name: 'Headline Analyzer', description: 'Analyze your headlines for emotional impact and SEO performance to drive more clicks and engagement.' },
  { slug: 'markdown-to-html', name: 'Markdown to HTML', description: 'Fast and reliable Markdown to HTML converter for developers and content creators to format web content.' },
  { slug: 'loan-calculator', name: 'Loan Calculator', description: 'Calculate monthly loan payments, interest rates, and total repayment amounts for personal or business loans.' },
  { slug: 'qr-code-generator', name: 'QR Code Generator', description: 'Create free, high-quality QR codes for URLs, text, and contact information to bridge offline and online marketing.' },
  { slug: 'keyword-density-checker', name: 'Keyword Density Checker', description: 'Analyze the keyword frequency and density of your content to optimize it for search engine rankings.', affiliateLink: 'https://seranking.com/?ga=5009081&source=link' },
  { slug: 'break-even-calculator', name: 'Break-Even Calculator', description: 'Determine your break-even point in units and dollars to make informed pricing and business decisions.' },
  { slug: 'meta-tag-previewer', name: 'Meta Tag Previewer', description: 'Preview how your website meta titles and descriptions will appear in Google search results for better CTR.', affiliateLink: 'https://seranking.com/?ga=5009081&source=link' },
  { slug: 'email-subject-tester', name: 'Email Subject Tester', description: 'Test and optimize your email subject lines to improve open rates and avoid spam filters.' }
];
