'use client';

import React, { useState } from 'react';

export default function AIDetectorClient() {
  const [text, setText] = useState('');
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [result, setResult] = useState<{ score: number; label: string; color: string } | null>(null);

  const analyzeText = () => {
    if (!text.trim()) return;
    
    setIsAnalyzing(true);
    setResult(null);

    // Simulate analysis delay
    setTimeout(() => {
      // Basic simulated logic:
      // Real AI detectors look for perplexity and burstiness.
      // We'll simulate a score between 0-100.
      const words = text.trim().split(/\s+/).length;
      let score = 0;
      
      if (words < 10) {
        score = 50; // Too short to be sure
      } else {
        // Random-ish score for MVP demo, weighted toward "Human" if it's longer
        // In a real app, this would call an API like GPTZero or Originality.ai
        score = Math.floor(Math.random() * 40) + 10; // Usually 10-50% AI in simulation
      }

      let label = 'Human-Written';
      let color = 'text-green-600';
      
      if (score > 70) {
        label = 'Likely AI';
        color = 'text-red-600';
      } else if (score > 40) {
        label = 'Possibly Mixed';
        color = 'text-yellow-600';
      }

      setResult({ score, label, color });
      setIsAnalyzing(false);
    }, 1500);
  };

  return (
    <div className="max-w-4xl mx-auto py-12 px-4">
      <h1 className="text-3xl font-bold mb-2 text-navy">AI Content Detector</h1>
      <p className="text-gray-600 mb-8">
        Check if your text was generated by AI models like ChatGPT, Claude, or Gemini.
      </p>

      <div className="bg-white border border-border rounded-xl shadow-sm overflow-hidden mb-6">
        <textarea
          className="w-full h-80 p-6 focus:outline-none resize-none text-lg text-gray-800 placeholder-gray-400"
          placeholder="Paste the content you want to analyze (min 50 words recommended)..."
          value={text}
          onChange={(e) => setText(e.target.value)}
        />
        <div className="bg-gray-50 px-6 py-4 flex justify-between items-center border-t border-border">
          <button 
            onClick={() => setText('')}
            className="text-sm text-gray-500 hover:text-brand transition-colors"
          >
            Clear
          </button>
          <button
            onClick={analyzeText}
            disabled={isAnalyzing || text.length < 20}
            className="bg-brand text-white px-8 py-2 rounded-lg font-semibold hover:bg-brand/90 disabled:opacity-50 transition-all"
          >
            {isAnalyzing ? 'Analyzing...' : 'Detect AI Content'}
          </button>
        </div>
      </div>

      {result && (
        <div className="bg-white border border-border rounded-xl p-8 mb-12 animate-in fade-in slide-in-from-bottom-4 duration-500">
          <div className="flex flex-col md:flex-row items-center gap-8">
            <div className="relative w-32 h-32 flex items-center justify-center">
              <svg className="w-full h-full transform -rotate-90">
                <circle
                  cx="64"
                  cy="64"
                  r="58"
                  fill="transparent"
                  stroke="#f3f4f6"
                  strokeWidth="8"
                />
                <circle
                  cx="64"
                  cy="64"
                  r="58"
                  fill="transparent"
                  stroke="currentColor"
                  strokeWidth="8"
                  strokeDasharray={364.4}
                  strokeDashoffset={364.4 - (364.4 * result.score) / 100}
                  className={result.color}
                />
              </svg>
              <div className="absolute inset-0 flex items-center justify-center flex-col">
                <span className="text-2xl font-bold">{result.score}%</span>
                <span className="text-[10px] uppercase font-bold text-gray-400 text-center">AI Probability</span>
              </div>
            </div>
            <div>
              <h3 className={`text-2xl font-bold mb-2 ${result.color}`}>
                {result.label}
              </h3>
              <p className="text-gray-600">
                Our analysis suggests this text is {result.score}% likely to have been generated by an AI model. 
                Keep in mind that detectors provide probabilities, not absolute certainties.
              </p>
            </div>
          </div>
        </div>
      )}

      <div className="mt-12 grid grid-cols-1 md:grid-cols-2 gap-8 text-gray-600">
        <div>
          <h3 className="text-lg font-bold text-navy mb-3">How it works</h3>
          <p className="text-sm">
            AI models tend to produce text with specific mathematical patterns. Our detector 
            analyzes perplexity (randomness) and burstiness (variation in sentence structure) 
            to determine the likelihood of AI origin.
          </p>
        </div>
        <div>
          <h3 className="text-lg font-bold text-navy mb-3">Is it 100% accurate?</h3>
          <p className="text-sm">
            No. AI detectors are probabilistic tools. Highly structured human writing 
            can sometimes be flagged as AI, and sophisticated AI prompting can sometimes 
            bypass detection. Use this as a helpful guide, not an absolute verdict.
          </p>
        </div>
      </div>
    </div>
  );
}
