import { Metadata } from 'next';
import AIDetectorClient from './AIDetectorClient';

export const metadata: Metadata = {
  title: 'AI Content Detector | Free Online Tool | WriteToolkit',
  description: 'Check if your text was generated by AI models like ChatGPT, Claude, or Gemini with our AI content detector.',
};

export default function Page() {
  return <AIDetectorClient />;
}
