import { Metadata } from 'next';
import AIDetectorClient from './AIDetectorClient';
import Breadcrumbs from '@/components/Breadcrumbs';
import AffiliateBlock from '@/components/AffiliateBlock';

export const metadata: Metadata = {
  title: 'AI Content Detector | Free Online Tool | WriteToolkit',
  description: 'Check if your text was generated by AI models like ChatGPT, Claude, or Gemini with our AI content detector.',
  alternates: {
    canonical: '/tools/ai-detector',
  },
};

export default function Page() {
  return (
    <div className="container mx-auto py-8">
      <Breadcrumbs 
        items={[
          { href: '/', label: 'Home' },
          { href: '/tools', label: 'Tools' },
          { href: '/tools/ai-detector', label: 'AI Detector' }
        ]} 
      />
      <AIDetectorClient />
      <AffiliateBlock placement="toolPage" />
    </div>
  );
}
